### ISSUE TITLE
Clean up mail.py

### ISSUE THREAD

**Issue by tzussman** [cs3157/seatingcharts#13]
We don't really use `mail.py` anymore for a variety of reasons, but now that it's been converted to Python 3, there are a number of enhancements that can be made:

- Use argparse and avoid hardcoding name, email, subject, and reply-to fields
- Switch to more modern string formatting
- Use context manager for file

It may also not work for Barnard emails since columbia.edu emails don't automatically redirect anymore

**Comment by JakasaurusRex** [comment]
#20
